server:
  port: 8082

app:
  kafka:
    topics:
      user-registered: "user-registered"

spring:
  # H2 ?????? ??
  datasource:
    url: jdbc:h2:mem:authTestDB;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # H2 ? ?? ??? (???)
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop  # ?????? ???? ??? ???
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

# ?? ??
  devtools:
    restart:
      enabled: true

# ?? (SQL ???)
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
